### PR TITLE
Fixed command declaration

### PR DESCRIPTION
**Pull request by marioradu05**

### CODE REVIEW

**Review by arhimede — CHANGES_REQUESTED** [review]
@alexmerlin i am against approving this one.
We want that all dot packages to use dot-cli, not symfony.
I do not understand why we are uaing symfony since is *not* requested in composer.json

**Comment by alexmerlin** [comment]
> @alexmerlin i am against approving this one. We want that all dot packages to use dot-cli, not symfony. I do not understand why we are uaing symfony since is _not_ requested in composer.json

You are right, `symfony/console` is not required in `composer.json`.
BUT, `composer.json` requires [dotkernel/dot-cli](https://github.com/dotkernel/dot-geoip/blob/3.0/composer.json#L26), which requires [laminas/laminas-cli](https://github.com/dotkernel/dot-cli/blob/3.0/composer.json#L28), which requires [syfony/console](https://github.com/laminas/laminas-cli/blob/1.11.x/composer.json#L33).
So, in the end, we (us and most frameworks) are all using Symfony's CLI package.
Hence, we need to adapt our commands in order to be able to keep using their package (as long as Laminas did not invent something that automatically adds the `AsCommand` attribute).

**Comment by arhimede** [comment]
> > @alexmerlin i am against approving this one. We want that all dot packages to use dot-cli, not symfony. I do not understand why we are uaing symfony since is _not_ requested in composer.json
> 
> You are right, `symfony/console` is not required in `composer.json`. BUT, `composer.json` requires [dotkernel/dot-cli](https://github.com/dotkernel/dot-geoip/blob/3.0/composer.json#L26), which requires [laminas/laminas-cli](https://github.com/dotkernel/dot-cli/blob/3.0/composer.json#L28), which requires [syfony/console](https://github.com/laminas/laminas-cli/blob/1.11.x/composer.json#L33). So, in the end, we (us and most frameworks) are all using Symfony's CLI package. Hence, we need to adapt our commands in order to be able to keep using their package (as long as Laminas did not invent something that automatically adds the `AsCommand` attribute).

The key point here is that in :
dot-geoip library 
And in all other dot-* libraries 
Instead of "use Symfony\console" 
We must have "use Dot-cli\console" or similar.

All dot libraries (except dot-cli) must not use directly Symfony\consoe

**Comment by alexmerlin** [comment]
Now I understand why you want to avoid having Symfony namespaces in the Dot libraries.

@MarioRadu already started working on this, but he encountered the following problem so he asked for my advice.

(The below applies to all classes/methods that he would have to override.)
For example:
In the class **Dot\Cli\Component\Console\Command\Command** he would have to do the following:
```
<?php

class Command
{
	// Replace Symfony's method
	protected function execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int
	{
		...
	}

	// with DotCli's method
	protected function execute(Dot\Cli\Component\Console\Input\InputInterface $input, Dot\Cli\Component\Console\Output\OutputInterface $output): int
	{
		...
	}
}
```
But, this is not allowed because PHP will throw an exception if you try to modify a method's signature:

> PHP Fatal error:  Declaration of Dot\Cli\Command\DemoCommand::execute(Dot\Cli\Component\Console\Input\InputInterface $input, Dot\Cli\Component\Console\Output\OutputInterface $output): int must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /var/www/dot-cli.local/html/vendor/dotkernel/dot-cli/src/Command/DemoCommand.php on line 26

Read more on this [here](https://www.php.net/manual/en/language.oop5.basic.php#language.oop.lsp).


There could be another solution (theoretically): decorating each of Symfony's classes/methods. For example:
When running a command, Symfony's `execute` method is called; but with the new solution, we would call our method, that will call Symfony's method.
Let's take the same class **Dot\Cli\Component\Console\Command\Command**, this time with the following code:
```
<?php

namespace Dot\Cli\Component\Console\Command;

class Command
{
	protected function __construct(
		private Symfony\Component\Console\Command\Command $command,
		private Symfony\Component\Console\Input\InputInterface $input,
		private Symfony\Component\Console\Output\OutputInterface $output,
	): int {
	}

	protected function execute(Dot\Cli\Component\Console\Input\InputInterface $input, Dot\Cli\Component\Console\Output\OutputInterface $output): int
	{
		return $this->command->execute($this->input, $this->output);
	}
}
```
So, in this case GeoIpCommand would change to:
```
<?php

namespace Dot\GeoIp\Command;

class GeoIpCommand extends Dot\Cli\Component\Console\Command\Command
{
	// other methods...

	protected function execute(Dot\Cli\Component\Console\Input\InputInterface $input, Dot\Cli\Component\Console\Output\OutputInterface $output): int
	{
		...
	}
}
```
not needing any reference to Symfony's classes.

The problem is that this solution is a total overkill and I'm not even sure if it could work because it involves:
- creating a wrapper class for each of Symfony's classes
- injecting the required Symfony class instances in each wrapper class
- wrapping each method one by one

**Pull request merged**
